name: 'Dependabot Jira Advanced'
description: 'Create a Jira ticket of a configurable type when a dependabot with big impact is created.'

inputs:
  pat_token:
    description: The github personal access token.
    required: true
  jira_base_url:
    description: The base url of jira.
    required: true
  jira_user_email:
    description: The email of jira user to open the bug.
    required: true
  jira_api_token:
    description: The api token of jira of the user.
    required: true
  jira_project:
    description: The jira project that the bug will be opened.
    required: true
  jira_issue_type:
    description: The jira ticket issue type.
    required: true
    default: 'Security'
  jira_field:
    description: The jira ticket field.
    required: true
    default: 'Components'
  jira_field_value:
    description: The jira ticket field value.
    required: true
    default: 'engineering'
  cvss_threshold:
    description: The CVSS threshold that triggers jira ticket creation.
    required: true
    default: '9.0'

branding:
  color: red
  icon: target

runs:
  using: "composite"
  steps:
    - name: Fetch Dependabot PR metadata
      id: dependabot-metadata
      uses: dependabot/fetch-metadata@dbb049abf0d677abbd7f7eee0375145b417fdd34 # v2.2.0
      with:
        alert-lookup: true
        github-token: ${{ inputs.pat_token }}

    - name: Login to jira
      id: jira-login
      if: ${{ steps.dependabot-metadata.outputs.cvss >= inputs.cvss_threshold }}
      uses: atlassian/gajira-login@45fd029b9f1d6d8926c6f04175aa80c0e42c9026 # v3
      env:
        JIRA_BASE_URL: ${{ inputs.jira_base_url }}
        JIRA_USER_EMAIL: ${{ inputs.jira_user_email }}
        JIRA_API_TOKEN: ${{ inputs.jira_api_token }}

    - name: Open jira bug
      id: open-jira-bug
      if: ${{ steps.dependabot-metadata.outputs.cvss >= inputs.cvss_threshold }}
      uses: atlassian/gajira-create@59e177c4f6451399df5b4911c2211104f171e669 #v3
      with:
        project: ${{ inputs.jira_project }}
        issuetype: ${{ inputs.jira_issue_type }}
        summary: |
          🚨 [${{github.event.repository.name }}] ${{github.event.pull_request.title }}
        description: |
          Dependabot opened a [Pull Request| ${{ github.event.pull_request.html_url }}] that fixes a security vulnerability with [CVSS| https://en.wikipedia.org/wiki/Common_Vulnerability_Scoring_System ] score ${{ steps.dependabot-metadata.outputs.cvss }}.
          [GitHub Advisory Database entry| https://github.com/advisories/${{steps.dependabot-metadata.outputs.ghsa-id}} ]
        fields: '{"${{inputs.jira_field}}": ["${{inputs.jira_field_value}}"]}'
